INSERT INTO heroes (id, name) VALUES (13, 'Bombasto');
INSERT INTO heroes (id, name) VALUES (14, 'Celeritas');
INSERT INTO heroes (id, name) VALUES (18, 'Dr IQ');
INSERT INTO heroes (id, name) VALUES (11, 'Dr Nice');
INSERT INTO heroes (id, name) VALUES (17, 'Dynama');
INSERT INTO heroes (id, name) VALUES (19, 'Magma');
INSERT INTO heroes (id, name) VALUES (15, 'Magneta');
INSERT INTO heroes (id, name) VALUES (12, 'Narco');
INSERT INTO heroes (id, name) VALUES (16, 'RubberMan');
INSERT INTO heroes (id, name) VALUES (20, 'Tornado');

-- INSERT INTO heroes (name) VALUES ('Bombasto');
-- INSERT INTO heroes (name) VALUES ('Celeritas');
-- INSERT INTO heroes (name) VALUES ('Dr IQ');
-- INSERT INTO heroes (name) VALUES ('Dr Nice');
-- INSERT INTO heroes (name) VALUES ('Dynama');
-- INSERT INTO heroes (name) VALUES ('Magma');
-- INSERT INTO heroes (name) VALUES ('Magneta');
-- INSERT INTO heroes (name) VALUES ('Narco');
-- INSERT INTO heroes (name) VALUES ('RubberMan');
-- INSERT INTO heroes (name) VALUES ('Tornado');
